"use client";

import React from 'react';

export default function ReportsPage() {
  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex justify-between items-end border-b border-gray-700 pb-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Shift Reports</h1>
          <p className="text-gray-400 mt-1">Automated shift summaries generated by the LLM.</p>
        </div>
      </div>

      <div className="bg-gray-800 rounded-xl p-6 border border-gray-700 shadow-sm">
        <h3 className="text-lg font-medium text-white mb-4">Latest Shift Summary</h3>
        <div className="bg-gray-900 rounded p-6 border border-gray-700 space-y-4">
          <p className="text-sm text-gray-300 leading-relaxed">
            <strong>Shift B (14:00 - 22:00) Summary:</strong><br /><br />
            During this shift, PM1 completed 3 successful grade transitions and experienced 1 off-spec event during the transition from GRADE-A to GRADE-C. 
            The off-spec event was predicted 45 minutes in advance, primarily attributed to abnormally high headbox pressure and stock flow rate.
            Operators accepted the system's recommendation to reduce headbox pressure by 0.2 bar, which stabilised the process within 30 minutes, 
            minimising broke production. All sensors are reporting normally, and there were no critical safety interaction rules triggered.
          </p>
          <div className="pt-4 border-t border-gray-800 flex justify-end">
            <button className="text-sm bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded transition-colors font-medium">
              Export PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
